# Dockerfile.jenkins
FROM jenkins/jenkins:lts

USER root

# Instalamos el cliente Docker desde los repositorios oficiales de Debian
RUN apt-get update && \
    apt-get install -y docker.io && \
    rm -rf /var/lib/apt/lists/*

USER jenkins