# Dockerfile.jenkins
FROM jenkins/jenkins:lts

USER root

# Instalamos sólo el cliente Docker
RUN apt-get update && \
    apt-get install -y docker-ce-cli && \
    rm -rf /var/lib/apt/lists/*

USER jenkins