name: CI and Docker Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

env:
  IMAGE_NAME: proyectogps-backend 

jobs:
  build-and-dockerize:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build Backend (Maven)
      working-directory: Back/Backend
      run: mvn clean install

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Debug secrets (temporal)
      run: |
        echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}"
        echo "DOCKER_PASSWORD length=${{ secrets.DOCKER_PASSWORD != '' && secrets.DOCKER_PASSWORD.length || 0 }}"


    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./Back/Backend
        file: ./Back/Backend/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
    - name: Replace image tag in Kubernetes manifest
      run: |
        sed -i "s|matiasjara1901244/proyectogps-backend:__TAG__|matiasjara1901244/proyectogps-backend:${{ github.sha }}|g" k8s/backend-deployment.yaml

    - name: Commit and push updated deployment.yaml
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add k8s/backend-deployment.yaml

        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update backend image tag to ${{ github.sha }}"
          git push
        fi