name: CI

on:
  push:
    branches: [main]  # Detecta cambios en la rama principal
  pull_request:
    branches: [main]  # Detecta pull requests hacia la rama principal

jobs:
  build:
    runs-on: ubuntu-latest  # Usa Ubuntu como el sistema operativo

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Extrae el código del repositorio

    # Backend (Java + Maven)
    - name: Set up Java
      uses: actions/setup-java@v3  # Configura Java
      with:
        java-version: '17'  # Define la versión de Java
        distribution: 'temurin'  # Usar la distribución Temurin de OpenJDK

    - name: Build Backend
      working-directory: ./backend  # Asegúrate de que 'backend' es la carpeta correcta
      run: mvn clean install  # Ejecuta Maven para compilar el backend